"""Timestamped personal listening-event streams — a new data modality.

The existing :mod:`playlistcont.data` package models *playlists*: unordered-in-time
bags of tracks curated by many users.  This package models something different and
complementary: a **single person's listening history** as a chronological stream of
*play events*, each with a timestamp, a track, how long it was played and whether it
was skipped.  This is the raw material for a personal-analytics dashboard (Phase 1)
and for taste-over-time change-point detection (Phase 3).

Two provenances feed the same container:

* ``"synthetic"`` — generated by :mod:`playlistcont.history.synthetic` with a fully
  described :class:`HistoryGroundTruth`: which taste *regimes* the listener passed
  through, exactly when their taste changed, and a set of deliberate *traps* (spans
  that look like a change but are not).  Because the truth is planted, later
  change-point detectors can be scored honestly.
* ``"spotify_export"`` — parsed from a real Spotify GDPR data export by
  :mod:`playlistcont.history.spotify_export`.  Real data has **no ground truth**
  (``ground_truth`` is ``None``).

Honest limitations of this modality (stated up front, in the spirit of
``data/schema.py`` and ``data/real_features.py``):

* **A play is not a preference.**  ``ms_played`` and ``skipped`` are noisy proxies
  for "did they like it"; autoplay, radio and background listening all leak in.
* **The synthetic ground truth is a *model* of taste change,** not a claim about how
  real listening evolves.  Regimes are piecewise-stationary archetype mixtures with
  linear drift transitions — a deliberately simple structure a detector *should* be
  able to recover.  Real taste is messier; scoring on synthetic data measures
  whether a detector works on the planted structure, nothing more.
* **Real exports carry no interpretable axis features.**  Synthetic tracks come with
  the taste-engine axis vector baked in (:data:`playlistcont.data.schema.AXES`); real
  tracks get axes only if you later join an audio-features table
  (see :mod:`playlistcont.history.features`), and even then via the documented
  proxies of ``data/real_features.py``.  ``track_uri`` is ``None`` for the thin
  "Account data" basic export, which has no URIs at all.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Dict, List, Literal, Optional

import numpy as np

# ---------------------------------------------------------------------------
# The event and its track
# ---------------------------------------------------------------------------


@dataclass
class ListenEvent:
    """A single play in a personal listening stream.

    Field names mirror the Spotify extended-export record so the loader is a thin
    rename.  ``ts`` is always timezone-aware UTC.  ``track_uri`` is ``None`` only for
    basic-export rows (which lack URIs); ``skipped``/``platform`` are ``None`` when the
    source did not record them.
    """

    ts: datetime                      # timezone-aware, UTC
    track_uri: Optional[str]          # "spotify:track:<22-char id>" or None (basic export)
    track_name: str
    artist_name: str
    ms_played: int
    album_name: Optional[str] = None
    skipped: Optional[bool] = None
    platform: Optional[str] = None


@dataclass
class HistoryTrack:
    """Track-level metadata for a listening history, keyed by ``track_uri``.

    ``features`` is the interpretable taste-engine axis vector
    (:data:`playlistcont.data.schema.AXES`, length :data:`N_AXES`) when known —
    always present for synthetic tracks, and for real tracks only after an
    audio-features join (:mod:`playlistcont.history.features`).  ``archetype`` records
    the generating archetype for synthetic tracks (``None`` for real ones).

    ``extended`` is an optional widened per-track record (popularity, danceability,
    speechiness, loudness, liveness, key, mode, duration_ms) attached by
    :func:`playlistcont.history.features.attach_extended_features` — ``None`` until
    that join runs, and individual values inside may be ``None`` (nullable source
    columns).
    """

    track_uri: str
    track_name: str
    artist_name: str
    album_name: Optional[str] = None
    album_uri: Optional[str] = None
    features: Optional[np.ndarray] = None
    archetype: Optional[str] = None
    extended: Optional[dict] = None


# ---------------------------------------------------------------------------
# Ground-truth types for synthetic histories
# ---------------------------------------------------------------------------


@dataclass
class RegimeSpec:
    """One piecewise-stationary span of taste.

    ``mixture`` maps archetype name -> weight (weights sum to 1); a single-key mixture
    is a "pure" regime.  Regimes returned by the generator **partition** the timeline:
    ``regimes[0].start == start_date``, ``regimes[-1].end == start_date + n_days`` and
    ``regimes[i].end == regimes[i + 1].start``.  ``end`` is exclusive.
    """

    start: date
    end: date                         # exclusive
    mixture: Dict[str, float]         # archetype name -> weight (sums to 1)
    events_per_day: float
    label: str


ChangeKind = Literal["abrupt", "drift_start", "drift_end"]


@dataclass
class PlantedChange:
    """A planted taste-change landmark a detector is expected to find.

    An abrupt transition contributes a single ``"abrupt"`` change on the boundary date.
    A gradual transition contributes a ``"drift_start"`` and a ``"drift_end"`` bracketing
    the linear-interpolation window.
    """

    date: date
    kind: ChangeKind
    description: str


TrapKind = Literal["volume_only", "binge"]


@dataclass
class Trap:
    """A span that looks like a change but is NOT a taste change.

    Planted so change-point detectors can be scored on *not* flagging them:

    * ``"volume_only"`` — listening volume (events/day) shifts sharply while the
      archetype mixture (and therefore the mean axis vector) is unchanged.
    * ``"binge"`` — a single album/track dominates a short span while the underlying
      mixture is unchanged.
    """

    kind: TrapKind
    start: date
    end: date                         # exclusive
    description: str


@dataclass
class SeasonalSpan:
    """An annotated seasonal overlay (e.g. a December holiday bump).

    Seasonal effects are recurring and expected, so they are recorded here but
    deliberately **not** added to :attr:`HistoryGroundTruth.change_points`.
    """

    start: date
    end: date                         # exclusive
    archetype: str
    description: str


@dataclass
class HistoryGroundTruth:
    """Everything that was planted in a synthetic history."""

    regimes: List[RegimeSpec]
    change_points: List[PlantedChange]
    traps: List[Trap]
    seasonal_spans: List[SeasonalSpan]
    seed: int
    params: Dict[str, object]         # generator parameters (start_date, n_days, ...)


# ---------------------------------------------------------------------------
# The container
# ---------------------------------------------------------------------------


Provenance = Literal["synthetic", "spotify_export"]


@dataclass
class ListeningHistory:
    """A single person's chronological listening stream plus track metadata.

    * ``events`` — :class:`ListenEvent` list sorted ascending by ``ts``.
    * ``tracks`` — ``track_uri -> HistoryTrack`` (features present when known).
    * ``provenance`` — ``"synthetic"`` or ``"spotify_export"``.
    * ``ground_truth`` — the planted truth for synthetic data; ``None`` for real data.
    """

    events: List[ListenEvent]
    tracks: Dict[str, HistoryTrack]
    provenance: Provenance
    ground_truth: Optional[HistoryGroundTruth] = field(default=None)

    # ---- convenience ---------------------------------------------------
    @property
    def n_events(self) -> int:
        return len(self.events)

    @property
    def n_tracks(self) -> int:
        return len(self.tracks)

    def span(self) -> Optional[tuple[datetime, datetime]]:
        """(first ts, last ts), or ``None`` if there are no events."""
        if not self.events:
            return None
        return self.events[0].ts, self.events[-1].ts

    def is_sorted(self) -> bool:
        return all(
            self.events[i].ts <= self.events[i + 1].ts
            for i in range(len(self.events) - 1)
        )
